import type { Locale } from "./i18n";

export const copy = {
  vi: {
    brandNote: "AI × MQL5 × Mã nguồn mở",
    navigation: {
      home: "Trang chủ",
      project: "MQL5 CodeGraph",
      articles: "Bài viết",
      projects: "Dự án",
      about: "Giới thiệu",
      community: "Cộng đồng",
      openMenu: "Mở menu",
      closeMenu: "Đóng menu",
      switchLanguage: "Chuyển sang English",
    },
    theme: { light: "Chuyển sang giao diện sáng", dark: "Chuyển sang giao diện tối" },
    home: {
      eyebrow: "PROJECT INTELLIGENCE · PUBLIC BETA",
      title: "Biến code MQL5 thành bản đồ mà AI có thể hiểu.",
      lead: "Junet.store chia sẻ kỹ thuật AI, MQL5 và các dự án mã nguồn mở — bắt đầu với MQL5 CodeGraph, công cụ phân tích local giúp truy vết kiến trúc, tác động và ngữ cảnh có bằng chứng.",
      primary: "Khám phá MQL5 CodeGraph",
      secondary: "Cài v0.3.0",
      telegram: "Tham gia Interest AI MQL5",
      proofTitle: "Bằng chứng trước phỏng đoán",
      proofBody: "Phân biệt quan hệ lấy từ mã nguồn, resolver, runtime đã biết và suy luận. Kết quả thiếu luôn đi kèm diagnostics.",
      localTitle: "Local-first, không cần API key",
      localBody: "Core analyzer, CLI, dashboard loopback và MCP local không cần tài khoản cloud hay model key.",
      communityTitle: "Cho đi để cộng đồng cùng lớn",
      communityBody: "Mã nguồn MIT, thảo luận thiết kế công khai, bug có thể tái hiện và ghi nhận người đóng góp.",
      latest: "Bắt đầu từ kiến thức thực hành",
      latestLead: "Năm bài nền tảng, viết đầy đủ bằng tiếng Việt và tiếng Anh.",
      mission: "Một nơi nhỏ cho những người muốn AI làm việc với code thật — có nguồn, có giới hạn, có cách kiểm chứng.",
    },
    common: {
      readArticle: "Đọc bài",
      viewRepo: "Xem mã nguồn",
      starRepo: "Star trên GitHub",
      copyInstall: "Sao chép lệnh cài",
      copied: "Đã sao chép",
      releaseNotes: "Ghi chú phát hành",
      joinTelegram: "Tham gia Telegram",
      allArticles: "Tất cả bài viết",
      minutes: "phút đọc",
      publicBeta: "Public beta",
      noProjects: "Dự án mới sẽ chỉ xuất hiện khi đã có mã nguồn công khai và bằng chứng sử dụng.",
    },
  },
  en: {
    brandNote: "AI × MQL5 × Open Source",
    navigation: {
      home: "Home",
      project: "MQL5 CodeGraph",
      articles: "Articles",
      projects: "Projects",
      about: "About",
      community: "Community",
      openMenu: "Open menu",
      closeMenu: "Close menu",
      switchLanguage: "Chuyển sang Tiếng Việt",
    },
    theme: { light: "Switch to light theme", dark: "Switch to dark theme" },
    home: {
      eyebrow: "PROJECT INTELLIGENCE · PUBLIC BETA",
      title: "Turn MQL5 code into a map AI can reason about.",
      lead: "Junet.store shares practical AI, MQL5, and open-source engineering — starting with MQL5 CodeGraph, a local analysis tool for evidence-backed architecture, impact, and context tracing.",
      primary: "Explore MQL5 CodeGraph",
      secondary: "Install v0.3.0",
      telegram: "Join Interest AI MQL5",
      proofTitle: "Evidence before guesses",
      proofBody: "Source calls, resolver links, known runtime behavior, and inference stay distinct. Incomplete results keep visible diagnostics.",
      localTitle: "Local-first, no API key required",
      localBody: "The core analyzer, CLI, loopback dashboard, and local MCP runtime need no cloud account or model key.",
      communityTitle: "Build in public, grow together",
      communityBody: "MIT source, open design discussions, reproducible bug reports, and visible contributor recognition.",
      latest: "Start with practical knowledge",
      latestLead: "Five foundation articles, fully written in Vietnamese and English.",
      mission: "A focused place for people who want AI to work with real code — with sources, limits, and proof.",
    },
    common: {
      readArticle: "Read article",
      viewRepo: "View repository",
      starRepo: "Star on GitHub",
      copyInstall: "Copy install command",
      copied: "Copied",
      releaseNotes: "Release notes",
      joinTelegram: "Join Telegram",
      allArticles: "All articles",
      minutes: "min read",
      publicBeta: "Public beta",
      noProjects: "New projects will appear only after public source and usable evidence exist.",
    },
  },
} satisfies Record<Locale, unknown>;

export function getCopy(locale: Locale) {
  return copy[locale];
}
